global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'nginx-prometheus-exporter:9113' ]       

  - job_name: 'backend-node-1'
    metrics_path: /metrics
    static_configs:
      - targets: [ ':9100' ]

  - job_name: 'backend-node-2'
    metrics_path: /metrics
    static_configs:
      - targets: [ ':9100' ]        

  - job_name: 'backend-node-3'
    metrics_path: /metrics
    static_configs:
      - targets: [ ':9100' ] 

  - job_name: 'backend-api-1'
    metrics_path: /metrics
    static_configs:
      - targets: [ ':5000' ]     

  - job_name: 'backend-api-2'
    metrics_path: /metrics
    static_configs:
      - targets: [ ':5000' ]                     

  - job_name: 'backend-api-3'
    metrics_path: /metrics
    static_configs:
      - targets: [ ':5000' ] 

